"""empty message

Revision ID: 02ac659b756b
Revises: 8ee3144f9db5
Create Date: 2019-11-27 07:50:56.797089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ac659b756b'
down_revision = '8ee3144f9db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('saved_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_draft_saved_timestamp'), ['saved_timestamp'], unique=False)
        batch_op.drop_index('ix_draft_edit_timestamp')
        batch_op.drop_column('pub_timestamp')
        batch_op.drop_column('edit_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pub_timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_draft_edit_timestamp', ['edit_timestamp'], unique=False)
        batch_op.drop_index(batch_op.f('ix_draft_saved_timestamp'))
        batch_op.drop_column('saved_timestamp')
        batch_op.drop_column('created_timestamp')

    # ### end Alembic commands ###
