"""empty message

Revision ID: 05498a94708f
Revises: 27de2f83b85f
Create Date: 2019-11-22 00:38:20.608075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05498a94708f'
down_revision = '27de2f83b85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
