"""empty message

Revision ID: 17e2b3db6559
Revises: 92eadfa727ea
Create Date: 2019-11-26 14:36:13.255925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e2b3db6559'
down_revision = '92eadfa727ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_publications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], name=op.f('fk_followed_publications_publication_id_publications')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_followed_publications_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'publication_id', name=op.f('pk_followed_publications'))
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(length=512), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_publications_creator_id_users'), 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_publications_creator_id_users'), type_='foreignkey')
        batch_op.drop_column('img')
        batch_op.drop_column('creator_id')

    op.drop_table('followed_publications')
    # ### end Alembic commands ###
