"""empty message

Revision ID: 66e0f3344d0f
Revises: 865e8331e42a
Create Date: 2019-10-31 00:13:14.448804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e0f3344d0f'
down_revision = '865e8331e42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_edit_timestamp'), 'posts', ['edit_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_edit_timestamp'), table_name='posts')
    # ### end Alembic commands ###
