"""empty message

Revision ID: 706d91884a86
Revises: 84b2cdb7c245
Create Date: 2019-10-28 16:03:48.172062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706d91884a86'
down_revision = '84b2cdb7c245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_administrator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_administrator')
    # ### end Alembic commands ###
