"""add amount to hearts

Revision ID: 75034009f3ab
Revises: a95e3d9630bb
Create Date: 2019-11-05 19:57:11.252472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75034009f3ab'
down_revision = 'a95e3d9630bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
