"""riched post

Revision ID: 80b3d70b364e
Revises: 3386b6f73b6d
Create Date: 2019-11-10 06:44:09.243914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b3d70b364e'
down_revision = '3386b6f73b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('subtitle')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
