"""add mutiple timestamp

Revision ID: 862127f89657
Revises: 05498a94708f
Create Date: 2019-11-22 14:00:18.936512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862127f89657'
down_revision = '05498a94708f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('created_timestamp')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('created_timestamp')

    # ### end Alembic commands ###
