"""empty message

Revision ID: 865e8331e42a
Revises: b065a0efcc72
Create Date: 2019-10-30 17:01:18.220991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865e8331e42a'
down_revision = 'b065a0efcc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer()))
    op.add_column('posts', sa.Column('edit_timestamp', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('pub_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_edit_timestamp'), 'posts', ['edit_timestamp'], unique=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'pub_date')
    op.drop_column('posts', 'edit_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('edit_date', sa.DATETIME(), nullable=True))
    # op.add_column('posts', sa.Column('pub_date', sa.DATETIME(), nullable=True))
    # op.add_column('posts', sa.Column('user_id', sa.INTEGER(), nullable=False))

    op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'pub_date')
    op.drop_column('posts', 'edit_date')
    op.drop_index(op.f('ix_posts_edit_timestamp'), table_name='posts')
    # op.drop_column('posts', 'pub_timestamp')
    # op.drop_column('posts', 'edit_timestamp')
    # op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
