"""chage tittle to title

Revision ID: 8998d485330b
Revises: 8e17fdc69870
Create Date: 2019-11-04 03:37:32.222500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8998d485330b'
down_revision = '8e17fdc69870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('tittle', new_column_name='title')
        # batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=False))
        # batch_op.drop_column('tittle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title', new_column_name='tittle')
        # batch_op.add_column(sa.Column('tittle', sa.VARCHAR(length=80), nullable=False))
        # batch_op.drop_column('title')

    # ### end Alembic commands ###
