"""empty message

Revision ID: 8ee3144f9db5
Revises: 9fda33c5b623
Create Date: 2019-11-27 07:25:53.866070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee3144f9db5'
down_revision = '9fda33c5b623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=16), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_draft_author_id_users'), 'user', ['author_id'], ['id'])
        batch_op.drop_column('markdown')
        batch_op.drop_column('html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('markdown', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_draft_author_id_users'), type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('content')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
