"""empty message

Revision ID: 92eadfa727ea
Revises: b19bd3d01219
Create Date: 2019-11-25 15:27:22.021378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eadfa727ea'
down_revision = 'b19bd3d01219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_read'), ['read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_read'))
        batch_op.drop_column('read')

    # ### end Alembic commands ###
