"""empty message

Revision ID: 956eb777ec7c
Revises: 02ac659b756b
Create Date: 2019-11-27 19:29:06.856327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956eb777ec7c'
down_revision = '02ac659b756b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('publication_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=256), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_draft_publication_id_publications'), 'publications', ['publication_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_draft_publication_id_publications'), type_='foreignkey')
        batch_op.drop_column('tags')
        batch_op.drop_column('publication_id')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
