"""empty message

Revision ID: 9fda33c5b623
Revises: 17e2b3db6559
Create Date: 2019-11-26 19:11:20.914572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fda33c5b623'
down_revision = '17e2b3db6559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tags',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_users_tags_tag_id_tags'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_users_tags_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name='pk_users_tags')
    )
    # ### end Alembic commands ###
