"""add edit_timestamp to commments

Revision ID: acee706a9bba
Revises: 80b3d70b364e
Create Date: 2019-11-14 04:37:32.964241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acee706a9bba'
down_revision = '80b3d70b364e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comments_pub_timestamp'), ['pub_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_pub_timestamp'))
        batch_op.drop_column('edit_timestamp')

    # ### end Alembic commands ###
