"""update tables

Revision ID: b065a0efcc72
Revises: b6c0e699401b
Create Date: 2019-10-30 14:36:43.493356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b065a0efcc72'
down_revision = 'b6c0e699401b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###
