"""empty message

Revision ID: cdf9898c3341
Revises: 956eb777ec7c
Create Date: 2019-11-28 13:19:43.822010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf9898c3341'
down_revision = '956eb777ec7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_draft_reference_id_posts'), 'posts', ['reference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_draft_reference_id_posts'), type_='foreignkey')
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
